# Generated by Django 5.1.7 on 2025-04-15 17:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('visit_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)], verbose_name='Tanggal Kunjungan')),
                ('number_of_visitors', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah Pengunjung')),
                ('need_guide', models.BooleanField(default=False, verbose_name='Perlu Pemandu')),
                ('special_requests', models.TextField(blank=True, verbose_name='Permintaan Khusus')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Biaya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='village.destination')),
            ],
            options={
                'verbose_name': 'Reservasi',
                'verbose_name_plural': 'Reservasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
