# Generated by Django 5.2 on 2025-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='destination',
            name='operational_hour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jam Operasional'),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Harga'),
        ),
    ]
