# Generated by Django 5.2 on 2025-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_destination_category_destination_operational_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='operational_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
