# Generated by Django 5.1.7 on 2025-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
